nginx_exporter_version: "1.4.2"
nginx_exporter_port: 9113
nginx_exporter_listen_address: "0.0.0.0"
nginx_exporter_download_base: "https://github.com/nginx/nginx-prometheus-exporter/releases/download"
nginx_exporter_scrape_uri: "http://127.0.0.1:{{ metrics_proxy_port | default(9090) }}{{ nginx_stub_status_path | default('/stub_status') }}"
